name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required for pushing to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          persist-credentials: false

      - name: Super-linter
        uses: super-linter/super-linter/slim@v8.1.0 # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=docker_ucarp
          IMAGE_TAG=${{ github.sha }} # Or use 'latest' or a version number
          docker build . --tag ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}:${IMAGE_TAG}
          docker push ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}:${IMAGE_TAG}
